#!/bin/bash

set -e

if [ ! $# -eq 1 ]; then
  echo "Usage: ./docker-build <project>" >&2
  exit 1
fi

if [ "$1" != "ratelimit" ]; then
  echo "Only ratelimit builds supported for now" >&2
  exit 1
fi

PROJECT="$1"
BIN="bazel-bin/$PROJECT/$PROJECT"

bazel build -c opt "$PROJECT"
tar --xform "s%.*/%%" -cz "$BIN" "$PROJECT/Dockerfile" | \
  docker build -t "smyte/$PROJECT" -
