workspace(name = "smyte_db_examples")

# smyte-db
http_archive(
    name = "smyte",
    url = "https://github.com/smyte/smyte-db/archive/fb95ae0.tar.gz",
    strip_prefix = "smyte-db-fb95ae02e3bce04aeb4f9de2223777570492352e",
    sha256 = "7e1e60117a04f6051f5db91cffa2f60952f9b698091e3c8efa090957749e3ee5",
)

load("@smyte//third_party:workspace.bzl", "smyte_workspace")
smyte_workspace("smyte")
