package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gcs",
    srcs = [
        "GoogleCloudStorage.cpp",
    ],
    hdrs = [
        "GoogleCloudStorage.h"
    ],
    deps = [
        "//external:folly",
        "//external:glog",
        "//external:googleapis_storage",
    ],
)
